apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-kiali
  namespace: demo
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: kiali-server
    targetRevision: "1.22.1"
    helm:
      values: |
        auth:
          strategy: anonymous
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
