apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: ">0.0.0"
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec: {}   # <- sin PVC (usa emptyDir)
            retention: 15d
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]
