apiVersion: v1
kind: Service
metadata:
  name: test2
  labels:
    app: test2
spec:
  type: NodePort
  selector:
    app: test2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
