apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http


