apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
      nodePort: 30900   # ajusta si quieres
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30030
